### ISSUE TITLE
Themes won't show up on source built terminology

### ISSUE THREAD

**Issue by frankiejol** [sylveon/terminology-themes#8]
Hi. I have Terminology Version: 1.8.99 built from source.
I installed the terminology-themes following the guide because I couldn't find a package for my Ubuntu OS (20.04).
```make ; sudo make install ```
It looks like the themes are installed in /usr/shared but they won't show up in my terminal. I tried copying the themes from _/usr/share/terminology/themes_ to _/usr/local/share/terminology/_ and now there they are.

I wonder if that is very Ubuntu specific but maybe themes should be installed in /usr/local when building from source. In the end no big deal but I just wanted to suggest this for your consideration.

Thanks

**Comment by sylveon** [comment]
I based the makefile off my Arch install, in which Terminology does checks for themes in `/usr/share`. So either you are correct and this is Debian-specific, or it has to do with you using a built from source version.

Are you aware if there's any way to detect this? If not, the makefile would probably still default to `/usr/share` but I can offer a way to customize the prefix used.

**Comment by frankiejol** [comment]
As far as I know always I build anything from source in Debian and RedHat it goes to /usr/local. I can't figure a way to check if it is defined somewhere. Maybe you can test if directory _/usr/share/terminology_ does not exist but /_usr/local/share/terminology/_ does.

**Comment by sylveon** [comment]
I've put up a commit which adds a prefix option, so for your case you can use `sudo make install PREFIX=/usr/local`.

Note that this repo isn't really maintained because I don't use Linux as main operating system anymore.

It's apparently been pulled from Gentoo packages because it doesn't build anymore for them, and I have a PR opened since November 2019 and while I keep meaning to find time to merge it and boot a VM to update the website screenshots, it's low on my priority list.

So if they work for you, great! Might not in the future anymore unfortunately...
